# 이 파일은 train_dataset.csv를 기준으로 자동 생성되었습니다.
# 모델 학습과 예측 시 피처 순서를 통일하기 위해 사용됩니다.

ALL_MODEL_FEATURES = [
    'prdy_ctrt',
    'price_change_1',
    'price_change_5',
    'price_change_10',
    'price_vs_ma5',
    'price_vs_ma20',
    'tr_amount_change',
    'spread',
    'spread_pct',
    'buy_pressure',
    'buy_strength',
    'volatility_5',
    'volatility_10',
    'momentum_5',
    'momentum_10',
    'RSI_3',
    'SMA_3',
    'SMA_5',
    'Disparity_5',
    'ATR_3',
    'Vol_Ratio',
    'gcn_emb_0',
    'gcn_emb_1',
    'gcn_emb_2',
    'gcn_emb_3',
    'gcn_emb_4',
    'gcn_emb_5',
    'gcn_emb_6',
    'gcn_emb_7',
    'gcn_emb_8',
    'gcn_emb_9',
    'gcn_emb_10',
    'gcn_emb_11',
    'gcn_emb_12',
    'gcn_emb_13',
    'gcn_emb_14',
    'gcn_emb_15',
    'sentiment_score',
    'ai_score',
]
